language: scala
scala:
    - "2.10.4"
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6
before_install:
    - sudo apt-get update -qq
    - sudo apt-get remove -y libzmq3
    - sudo apt-get install -y libzmq-dev

